/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vandu.ui;

import com.vandu.dao.ShareData;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Văn Dự
 */
public class MainForm extends javax.swing.JFrame {

    private StudentManament pnlStudentManament = null;
    private MarksManament pnlMarksStudent = null;
    LoginDialog login = new LoginDialog(this, true);
    LoadingDialog loading = new LoadingDialog(this, true);
    
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        loading.setVisible(true);
        login.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnLogout = new javax.swing.JButton();
        btn_StudentManament = new javax.swing.JButton();
        btn_MarksManament = new javax.swing.JButton();
        btnAboutUs = new javax.swing.JButton();
        tplMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnLogout2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHeThong = new javax.swing.JMenu();
        menuSystem_logout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSystem_exit = new javax.swing.JMenuItem();
        menuQuanLi = new javax.swing.JMenu();
        menu_manamentStudents = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_MarksManament = new javax.swing.JMenuItem();
        menuTroGiup = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÍ SINH VIÊN");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout-icon.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);

        btn_StudentManament.setBackground(new java.awt.Color(255, 255, 255));
        btn_StudentManament.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Users-Student-Filled-icon.png"))); // NOI18N
        btn_StudentManament.setText("Quản lí sinh viên");
        btn_StudentManament.setFocusable(false);
        btn_StudentManament.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_StudentManament.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_StudentManament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StudentManamentActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_StudentManament);

        btn_MarksManament.setBackground(new java.awt.Color(255, 255, 255));
        btn_MarksManament.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ModernXP-07-Keys-icon.png"))); // NOI18N
        btn_MarksManament.setText("Quản lí điểm");
        btn_MarksManament.setFocusable(false);
        btn_MarksManament.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_MarksManament.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_MarksManament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MarksManamentActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_MarksManament);

        btnAboutUs.setBackground(new java.awt.Color(255, 255, 255));
        btnAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Info-icon.png"))); // NOI18N
        btnAboutUs.setText("Giới thiệu");
        btnAboutUs.setFocusable(false);
        btnAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAboutUs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAboutUs);

        tplMain.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRole.setText("Role : giảng viên");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/male_user_30px.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblUsername.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        lblUsername.setText("Nguyễn Văn A");

        btnLogout2.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User-Interface-Login-icon.png"))); // NOI18N
        btnLogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(btnLogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblUsername)
                        .addGap(9, 9, 9)
                        .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuHeThong.setText("Hệ thống");

        menuSystem_logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSystem_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout-icon 16px.png"))); // NOI18N
        menuSystem_logout.setText("Đăng Xuất");
        menuSystem_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSystem_logoutActionPerformed(evt);
            }
        });
        menuHeThong.add(menuSystem_logout);

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        menuHeThong.add(jSeparator1);

        menuSystem_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSystem_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close_window_20px.png"))); // NOI18N
        menuSystem_exit.setText("Thoát");
        menuSystem_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSystem_exitActionPerformed(evt);
            }
        });
        menuHeThong.add(menuSystem_exit);

        jMenuBar1.add(menuHeThong);

        menuQuanLi.setText("Quản lí");

        menu_manamentStudents.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_manamentStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Users-Student-Filled-icon 16px.png"))); // NOI18N
        menu_manamentStudents.setText("Quản lí sinh viên");
        menu_manamentStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_manamentStudentsActionPerformed(evt);
            }
        });
        menuQuanLi.add(menu_manamentStudents);
        menuQuanLi.add(jSeparator2);

        menu_MarksManament.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_MarksManament.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ModernXP-07-Keys-icon_16px.png"))); // NOI18N
        menu_MarksManament.setText("Quản lí điểm");
        menu_MarksManament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_MarksManamentActionPerformed(evt);
            }
        });
        menuQuanLi.add(menu_MarksManament);

        jMenuBar1.add(menuQuanLi);

        menuTroGiup.setText("Trợ giúp");
        menuTroGiup.add(jSeparator3);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Status-dialog-information-icon_16px.png"))); // NOI18N
        jMenuItem6.setText("Giới thiệu");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuTroGiup.add(jMenuItem6);

        jMenuBar1.add(menuTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tplMain))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(tplMain, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_manamentStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_manamentStudentsActionPerformed
        if (pnlStudentManament == null) {
            pnlStudentManament = new StudentManament();

            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/10207-man-student-light-skin-tone-icon.png"));
            tplMain.addTab("Quản lí sinh viên", icon, pnlStudentManament);
        }
        tplMain.setSelectedComponent(pnlStudentManament);
    }//GEN-LAST:event_menu_manamentStudentsActionPerformed

    private void menuSystem_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSystem_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSystem_exitActionPerformed

    private void btn_StudentManamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StudentManamentActionPerformed
        menu_manamentStudentsActionPerformed(evt);
    }//GEN-LAST:event_btn_StudentManamentActionPerformed

    private void menu_MarksManamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_MarksManamentActionPerformed
        if (pnlMarksStudent == null) {
            pnlMarksStudent = new MarksManament();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/ModernXP-07-Keys-icon.png"));
            tplMain.addTab("Quản lí điểm", icon, pnlMarksStudent);

        }
        tplMain.setSelectedComponent(pnlMarksStudent);
    }//GEN-LAST:event_menu_MarksManamentActionPerformed

    private void btn_MarksManamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MarksManamentActionPerformed
        menu_MarksManamentActionPerformed(evt);
    }//GEN-LAST:event_btn_MarksManamentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginDialog login = new LoginDialog(this, true);
        login.setVisible(true);
        procressLoginSucessful();

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void menuSystem_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSystem_logoutActionPerformed
        btnLogoutActionPerformed(evt);
    }//GEN-LAST:event_menuSystem_logoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        procressLoginSucessful();
    }//GEN-LAST:event_formWindowOpened

    private void btnLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout2ActionPerformed
        btnLogoutActionPerformed(evt);
    }//GEN-LAST:event_btnLogout2ActionPerformed

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        AboutUsDialog abouts = new AboutUsDialog(this, true);
        abouts.setVisible(true);
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        btnAboutUsActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void procressLoginSucessful() {
        lblUsername.setText("Username: " + ShareData.user.getUsername());
        lblRole.setText("Role : " + ShareData.user.getRole());
        tplMain.removeAll();
        pnlMarksStudent = null;
        pnlStudentManament = null;
        if (ShareData.user.getRole().equals("Giảng viên")) {
            menu_MarksManament.setEnabled(true);
            btn_MarksManament.setEnabled(true);
            btn_StudentManament.setEnabled(false);
            menu_manamentStudents.setEnabled(false);
        } else {
            menu_MarksManament.setEnabled(false);
            btn_MarksManament.setEnabled(false);
            btn_StudentManament.setEnabled(true);
            menu_manamentStudents.setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html ìifiiiiiiiiiiiiiiii
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btn_MarksManament;
    private javax.swing.JButton btn_StudentManament;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenu menuHeThong;
    private javax.swing.JMenu menuQuanLi;
    private javax.swing.JMenuItem menuSystem_exit;
    private javax.swing.JMenuItem menuSystem_logout;
    private javax.swing.JMenu menuTroGiup;
    private javax.swing.JMenuItem menu_MarksManament;
    private javax.swing.JMenuItem menu_manamentStudents;
    private javax.swing.JTabbedPane tplMain;
    // End of variables declaration//GEN-END:variables
}
